bd_map/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("map_app.urls"))

]

map_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "bd_map"

urlpatterns = [
    path('', views.index, name='index'),
    path('map',views.map,name='map'),
    path('upload',views.upload,name='upload'),
    path('top_sales',views.top_sales,name='top_sales'),
    path('top_changed_sales_areas',views.top_changed_sales,name='top_changed_sales'),
]

map_app/models.py
from django.db import models


# Create your models here.
class Income(models.Model):
	district_code = models.CharField(max_length=50)
	district_name = models.CharField(max_length=200)
	month = models.IntegerField()
	income_by_month = models.CharField(max_length=200)
	income_last_month = models.FloatField()
	income_difference = models.FloatField()
	income = models.FloatField()
	
	# def __str__(self):
	# 	return "{} ({}) total  : ".format(self.district_name, self.district_code)
	
	def save(self, *args, **kwargs):
		try:
			self.income, self.income_last_month, self.income_difference = round(self.income, 2), round(
				self.income_last_month, 2), abs(round(self.income_difference, 2))
			self.income = 0 if self.income < 0 else self.income
			self.income_last_month = 0 if self.income_last_month < 0 else self.income_last_month
			self.income_difference = 0 if self.income_difference < 0 else self.income_difference
			self.month = 1 if self.month < 0 else self.month
			super().save(*args, **kwargs)
		except TypeError as te:
			pass

# class DistrictInfo(models.Model):

map_app/views.py
# import logging
# import traceback
from functools import reduce
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .utils.utils import calculate_income, calculate_income_last_month, calculate_change
from .models import Income
import openpyxl


def map(request):
    income_obj_count = Income.objects.all().count()
    # check if the record is empty
    if income_obj_count > 1:
        return render(request, 'map.html')
    else:
        messages.error(request, 'Please insert data!', extra_tags='error')
        return HttpResponseRedirect('/')
    
    
def upload(request):
    return render(request, 'upload.html')


def top_sales(request):
    income_obj_count = Income.objects.all().count()
    # check if the record is empty
    if income_obj_count > 1:
        income_obj_top_list = Income.objects.order_by('income_last_month').reverse()[:10]
    
        context = {
            'income_obj_top_list': income_obj_top_list
        }
        return render(request, 'top_sales.html', context)
    else:
        messages.error(request, 'No Data to display!', extra_tags='error')
        return HttpResponseRedirect('/')


def top_changed_sales(request):
    income_obj_count = Income.objects.all().count()
    # check if the record is empty
    if income_obj_count > 1:
        income_obj_top_changed_list = Income.objects.order_by('income_difference').reverse()[:10]
        
        context_difference = {
            'income_obj_top_changed_list': income_obj_top_changed_list
        }
        return render(request, 'top_changed_sales.html', context_difference)

    else:
        messages.error(request, 'No Data to display!', extra_tags='error')
        return HttpResponseRedirect('/')
   
    
def save_to_db(wb):
    worksheet = wb["Upazila_Underweight_Stunted_Chi"]
    # print(worksheet)
    
    excel_data = list()
    district_dict = {}
    # iterating over the rows and
    # getting value from each cell in row
    for row in worksheet.iter_rows():
        row_data = list()
        for cell in row:
            if cell.value is None:
                cell.value = 0
            row_data.append(str(cell.value))
        if row_data[1] is not "District Name":
            district_dict[row_data[1]] = row_data[4]
        excel_data.append(row_data)
    
    del district_dict["District Code"]  # delete the cell's header
    
    for district_code, district_name in district_dict.items():
        # income_per_month, income_last_month, income_difference = ('',), 0.0, 0.0
        # try:
        #     income_per_month = calculate_income(district_code, excel_data)
        # except Exception as e:
        #     logging.error(traceback.format_exc())
        #     print(e)
        # try:
        #     income_last_month = calculate_income(district_code, excel_data)
        # except Exception as e:
        #     logging.error(traceback.format_exc())
        #     print(e)
        #
        # try:
        #     income_difference = calculate_income(district_code, excel_data)
        # except Exception as e:
        #     logging.error(traceback.format_exc())
        #     print(e)

        income_per_month = calculate_income(district_code, excel_data)
        income_last_month = calculate_income_last_month(district_code, excel_data)
        income_difference = calculate_change(district_code, excel_data)

        income_total = reduce(lambda x, y: x + y, income_per_month)
        
        try:
            obj = Income(district_code=district_code, district_name=district_name, month=3,
                         income_by_month=income_per_month, income_last_month=income_last_month,
                         income_difference=income_difference, income=income_total)
        
        except Income.DoesNotExist:
            obj = Income(district_code=district_code, district_name=district_name, month=3,
                         income_by_month=income_per_month, income_last_month=income_last_month,
                         income_difference=income_difference, income=income_total)
        obj.save()
    
    return


def index(request):
    if "GET" == request.method:
        return render(request, 'index.html')
    else:
        try:
            Income.objects.all().delete()  # Delete all the records
        except Income.DoesNotExist:
            print("Nothing to delete")
        
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size

        wb = openpyxl.load_workbook(excel_file)
        
        print(wb.active.title)
        m1, m2, m3 = wb.active.cell(
            row=1, column=8).value, wb.active.cell(row=1, column=9).value, wb.active.cell(row=1, column=10).value
        
        if wb.active.title == "Upazila_Underweight_Stunted_Chi" \
                and m1 == "month1" and m2 == "month2" and m3 == "month3":
            print("correct wb", wb.active.cell(row=1, column=9).value)
            save_to_db(wb)
            return render(request, 'map.html')
        else:
            messages.error(request, 'An error occurred!')
            return HttpResponseRedirect('/upload')
        # getting a particular sheet by name out of many sheets
        
        
        
        
        
        # income_list = Income.objects.all()
      
        
        # context = {
        #     'income_list' : income_list
        # }
        

        
        # return render(request, 'index.html', {"excel_data": excel_data})


        """check for iteration"""
        

        # if cell in worksheet['B'] and cell.value is not None:
        #     print(cell.value, end=" ")

        # for row in worksheet.iter_rows(min_row=1, min_col=1):
        #     for cell in row:
        #         # cell_dis = worksheet['B']
        #         # print(cell.value in worksheet['B'])
        #
        #         if cell in worksheet['B'] and cell.value is not None:
        #             print(cell.value, end=" ")
        #         # if cell in
        #     print()

        # for row in worksheet.iter_cols(min_row=1, min_col=1):
        #     for cell in row:
        #         if cell['District Code'].value == 4:
        #             if cell.value is not None:
        #                 print(cell.value, end=" ")
        #             # if cell.value==4 :
        #             #     print(cell.value)
        #     print()

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'bd_map/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bd_map/css/style.css' %}">
    <title>Sales Monitoring System - Home</title>

</head>
<body><br>
<h1>Welcome to Sales Monitoring System</h1>
{% if messages %}
    {% for message in messages %}
        <div class="alert">
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          <strong>Error!</strong> {{ message }}
        </div>
    {% endfor %}
{% endif %}

<a href="{% url 'bd_map:upload' %}">
    <button>Upload Excel File</button>
</a>

<br>
<a href="{% url 'bd_map:top_sales' %}">
    <button>Top Ten Sales Area</button>
</a>

<br>
<a href="{% url 'bd_map:top_changed_sales' %}">
    <button>Top Ten Sales Figure Changed Areas
    </button>
</a>

<br>
<a href="{% url 'bd_map:map' %}">
    <button>Graph Information System (Map)</button>
</a>
<br>


<a style="text-decoration: none;" href="{% static 'bd_map/files/Division_District_Upazilla_hiarachy.xlsx' %}"
   title="Download and Edit the last three columns">
    <button>Download Sample Excel File</button>
</a>


<br>
<hr style="border-top: 1px solid #4CAF50;">

{#        {% for row in excel_data %}#}
{#            {% for cell in row %}#}
{#                {{ cell }}&nbsp;&nbsp;#}
{#            {% endfor %}#}
{#            <br>#}
{#        {% endfor %}#}
</body>
</html>

templates/top_changed_sales.html
<!DOCTYPE html>
{% load static %}
{% load income_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'bd_map/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bd_map/css/style.css' %}">
    <title>Sales Monitoring System - Top Sales Figure Changed Areas</title>
    <!-- ChatJs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
</head>
<body>
<div class="tableContainer">
    <h2>Top Sales from last Month</h2>
    <table class="tableTopList">
        <tr>
            <th>District Name</th>
            <th>Sales Difference (BDT)</th>
        </tr>
        {% for item in income_obj_top_changed_list %}
            <tr>
                <td> {{ item.district_name }} </td>
                <td> {{ item.income_difference }} </td>
            </tr>
        {% endfor %}
    </table>
</div>
<p id="topChangedDistrict"> {% top_sales_difference_district_list %}</p>

<div class="chartContainer">
    <canvas id="topSalesDifferenceChart"></canvas>
</div>
<script>
    let ctx = document.getElementById('topSalesDifferenceChart').getContext('2d');
    let top_district = document.getElementById('topChangedDistrict').innerText.trim().slice(1, -1).replace(/'/g, '');  /*Get string containing District name list*/
    let topChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: top_district.split(","),  /*Convert string to array*/
            datasets: [{
                label: '# of Sales (BDT) ',
                data: {% top_sales_difference_income_list  %},
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255,99,178,0.2)',
                    'rgba(54, 162, 135, 0.2)',
                    'rgba(255, 106, 86, 0.2)',
                    'rgba(255, 206, 186, 0.2)',
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255,99,178,1)',
                    'rgba(54, 162, 135, 1)',
                    'rgba(255, 106, 86, 1)',
                    'rgba(255, 206, 186, 1)',

                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            responsive: true,
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Top Sales Last Month'
            }
        }
    });
</script>
</body>
</html></html>

templates/top_sales.html
<!DOCTYPE html>
{% load static %}
{% load income_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'bd_map/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bd_map/css/style.css' %}">
    <title>Sales Monitoring System - Top Sales Areas</title>
    <!-- ChatJs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
</head>
<body>
<div class="tableContainer">
    <h2>Top Sales from last Month</h2>
    <table class="tableTopList">
        <tr>
            <th>District Name</th>
            <th>Last month Sales (BDT)</th>
        </tr>
        {% for item in income_obj_top_list %}
            <tr>
                <td> {{ item.district_name }} </td>
                <td> {{ item.income_last_month }} </td>
            </tr>
        {% endfor %}
    </table>
</div>
<p id="topDistrict"> {% top_sales_district_list %}</p>

<div class="chartContainer">
    <canvas id="topSalesChart"></canvas>
</div>
<script>
    let ctx = document.getElementById('topSalesChart').getContext('2d');
    let top_district = document.getElementById('topDistrict').innerText.trim().slice(1, -1).replace(/'/g, '');  /*Get string containing District name list*/
    let topChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: top_district.split(","),  /*Convert string to array*/
            datasets: [{
                label: '# of Sales (BDT) ',
                data: {% top_sales_income_list  %},
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255,99,178,0.2)',
                    'rgba(54, 162, 135, 0.2)',
                    'rgba(255, 106, 86, 0.2)',
                    'rgba(255, 206, 186, 0.2)',
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255,99,178,1)',
                    'rgba(54, 162, 135, 1)',
                    'rgba(255, 106, 86, 1)',
                    'rgba(255, 206, 186, 1)',

                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            responsive: true,
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Top Sales Last Month'
            }
        }
    });
</script>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'bd_map/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bd_map/css/style.css' %}">
    <title>Sales Monitoring System - Upload </title>
</head>
<body>
<h2>Upload Excel File containing Sales Info For GIS</h2>
{% if messages %}
    {% for message in messages %}
        <div class="alert">
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          <strong>Error!</strong> {{ message }}
        </div>
    {% endfor %}
{% endif %}

<a href="{% static 'bd_map/files/Division_District_Upazilla_hiarachy.xlsx' %}"
   title="Download and Edit the last three columns">
    <button>Download Sample Excel File</button>
</a>
<form action="{% url 'bd_map:index' %}" method="post"
      enctype="multipart/form-data" onsubmit="return validateFileExtension(this.excel_file)" onload="this.reset()">
    {% csrf_token %}
    <input type="file"
           id="file"
           title="Upload excel file"
           accept=".xls,.xlsx"
           name="excel_file"
           onchange="return validateFileExtension(this)"
           required="required">
    <input type="submit"
           value="Upload"

    >
</form>
<script>
     function validateFileExtension(fld) {
    if(!/(\.xls|\.xlsx)$/i.test(fld.value)) {
        alert("Invalid  file type.");
        fld.form.reset();
        fld.focus();
        return false;
    }
    return true;
 }
</script>

</body>
</html>